version: "3.9"

services:
  database:
    container_name: database
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: finance

  #server:
  # image: node:18-alpine
  # container_name: server
  # working_dir: /home-finance
  # ports:
  #   - "3000:3000"
  # volumes:
  #   - ./:/home-finance
  # restart: unless-stopped
  # command: sh -c "wget -qO /bin/pnpm "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" && chmod +x /bin/pnpm && pnpm install && pnpm run dev"
